### ISSUE TITLE
Unbevel tool

### ISSUE THREAD

**Issue by RAFpz2015** [roosterMAP/rmKit#4]
I'm getting an error on this unbevel tool
```
Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rmKit-main\addon\arcadjust.py", line 331, in execute
    arc_adjust( rmmesh.bmesh, 0.0 )
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rmKit-main\addon\arcadjust.py", line 56, in arc_adjust
    p0, p1 = mathutils.geometry.intersect_line_line( a, b, c, d )
TypeError: cannot unpack non-iterable NoneType object

```

**Comment by roosterMAP** [comment]
I updated the op to catch this error and report it properly. It happens when the outgoing edges driving the unbevel/arcadjust are parallel or colinear. This kinda means its an invalid selection to begin with... but at least now it wont bring up a python error.
