### ISSUE TITLE
Arc Adjust Tool.

### ISSUE THREAD

**Issue by RAFpz2015** [roosterMAP/rmKit#5]
Currently getting this error when using Arc Adjust.

```
Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rmKit-main\addon\arcadjust.py", line 276, in modal
    self.execute( context )			
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rmKit-main\addon\arcadjust.py", line 254, in execute
    arc_adjust( bm, self.scale )
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rmKit-main\addon\arcadjust.py", line 56, in arc_adjust
    p0, p1 = mathutils.geometry.intersect_line_line( a, b, c, d )
TypeError: cannot unpack non-iterable NoneType object

```

**Comment by roosterMAP** [comment]
I updated the op to catch this error and report it properly. It happens when the outgoing edges driving the unbevel/arcadjust are parallel or colinear. This kinda means its an invalid selection to begin with... but at least now it wont bring up a python error.
